"""Celery tasks for template-based exports.

Generates Excel exports in the background, writing results to disk.
Uses per-template+date Redis locks to prevent duplicate runs.
"""

import asyncio
import os
import traceback
from datetime import datetime, time, timezone
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, Optional

from celery import Task

from server.workers.celery_app import celery_app
from server.logging_config import get_logger

logger = get_logger(name=__name__)


class ExportTask(Task):
    """Base class for export tasks with progress tracking."""

    def update_progress(self, step: str, percent: int):
        self.update_state(
            state='PROGRESS',
            meta={
                'current_step': step,
                'progress_percent': percent,
                'updated_at': datetime.now(timezone.utc).isoformat(),
            },
        )


def _export_path(export_dir: Path, template_name: str, date_str: str) -> Path:
    """Build the output path: {export_dir}/{template_name}/{template_name}_{YYYYMMDD}.xlsx"""
    return export_dir / template_name / f"{template_name}_{date_str}.xlsx"


def _lock_key(template_name: str, date_str: str) -> str:
    return f"export:lock:{template_name}:{date_str}"


@celery_app.task(
    bind=True,
    base=ExportTask,
    name='server.workers.tasks.export.run_export_task',
    queue='export',
    time_limit=600,   # 10 min hard limit
    soft_time_limit=540,  # 9 min soft limit
)
def run_export_task(
    self,
    template_name: str,
    evaluation_date_iso: str,
) -> Dict[str, Any]:
    """Run a template export as a background Celery task.

    Args:
        template_name: Registered export template name.
        evaluation_date_iso: ISO date string (YYYY-MM-DD).

    Returns:
        Dict with success flag, file_path, and metadata.
    """
    from server.settings import get_settings

    settings = get_settings()
    export_dir = settings.export_dir
    date_str = evaluation_date_iso.replace("-", "")
    out_path = _export_path(export_dir, template_name, date_str)
    lock_key = _lock_key(template_name, date_str)
    start_time = datetime.now(timezone.utc)

    redis_client = None
    lock_acquired = False

    try:
        from server.config.redis import get_redis_sync_client
        redis_client = get_redis_sync_client()

        # Acquire lock (5 min expiry as safety net)
        lock_acquired = redis_client.set(lock_key, self.request.id, nx=True, ex=300)

        if not lock_acquired:
            # Check if file was produced by another task while we waited
            if out_path.exists():
                return {
                    'success': True,
                    'cached': True,
                    'file_path': str(out_path),
                    'message': 'Export already generated by another task.',
                }
            running_job = redis_client.get(lock_key)
            return {
                'success': False,
                'message': f'Another export is running for this template+date (job: {running_job}).',
            }

        self.update_progress("Initializing export...", 0)

        # If file already on disk (race with cache check in API), return it
        if out_path.exists():
            return {
                'success': True,
                'cached': True,
                'file_path': str(out_path),
                'message': 'Export file already exists.',
            }

        # Run async export in a new event loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

        try:
            xlsx_bytes = loop.run_until_complete(
                _run_async_export(self, template_name, evaluation_date_iso)
            )
        finally:
            loop.close()

        self.update_progress("Writing file...", 90)

        # Ensure directory exists and write file
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(xlsx_bytes)

        self.update_progress("Completed", 100)

        logger.info(
            "Export completed: template={}, date={}, size={} bytes, path={}",
            template_name, evaluation_date_iso, len(xlsx_bytes), out_path,
        )

        return {
            'success': True,
            'cached': False,
            'file_path': str(out_path),
            'template_name': template_name,
            'evaluation_date': evaluation_date_iso,
            'file_size': len(xlsx_bytes),
            'started_at': start_time.isoformat(),
            'completed_at': datetime.now(timezone.utc).isoformat(),
        }

    except Exception as e:
        logger.exception("Export task failed: {}", str(e))
        return {
            'success': False,
            'message': f"Export failed: {str(e)}",
            'error': str(e),
            'traceback': traceback.format_exc(),
            'started_at': start_time.isoformat(),
            'failed_at': datetime.now(timezone.utc).isoformat(),
        }

    finally:
        if redis_client and lock_acquired:
            redis_client.delete(lock_key)


async def _run_async_export(
    task: ExportTask,
    template_name: str,
    evaluation_date_iso: str,
) -> bytes:
    """Run the async export logic inside the Celery worker."""
    from server.config.postgres import init_engine
    from server.jobs import get_session_factory_for_background
    from server.pipelines.controls.export.registry import get_template
    from server.settings import get_settings

    # Force template registration
    import server.pipelines.controls.export.templates  # noqa: F401

    settings = get_settings()

    # Ensure DB engine is ready (may already be initialised by worker_process_init)
    init_engine(settings.postgres_url, pool_size=3, max_overflow=5)

    evaluation_dt = datetime.combine(
        datetime.fromisoformat(evaluation_date_iso).date(),
        time.max,
        tzinfo=timezone.utc,
    )

    template_cls = get_template(template_name)
    template = template_cls()

    task.update_progress("Querying database...", 20)

    session_factory = get_session_factory_for_background()
    async with session_factory() as db:
        rows = await template.query(db, evaluation_dt)

    logger.info("Template '{}' returned {} rows", template_name, len(rows))

    task.update_progress("Building workbook...", 60)

    wb = template.build_workbook(rows, evaluation_dt)

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
