"""SurrealDB Schema Module.

This module provides schema definitions and setup functions for the SurrealDB
controls management system following the naming convention:
{layer}_{domain}_{kind}_{name}

Exports:
    - Table name constants from definitions
    - Schema setup functions (create_schema, drop_schema, reset_schema)
"""

from .definitions import (
    # Source Reference Tables
    SRC_CONTROLS_REF_RISK_THEME,
    SRC_CONTROLS_REF_ORG_FUNCTION,
    SRC_CONTROLS_REF_ORG_LOCATION,
    SRC_CONTROLS_REF_SOX_ASSERTION,
    SRC_CONTROLS_REF_CATEGORY_FLAG,
    # Source Main Tables
    SRC_CONTROLS_MAIN,
    SRC_CONTROLS_VERSIONS,
    # Source Relationship Tables
    SRC_CONTROLS_REL_HAS_RISK_THEME,
    SRC_CONTROLS_REL_HAS_RELATED_FUNCTION,
    SRC_CONTROLS_REL_HAS_RELATED_LOCATION,
    SRC_CONTROLS_REL_HAS_SOX_ASSERTION,
    SRC_CONTROLS_REL_HAS_CATEGORY_FLAG,
    # AI Model Tables
    AI_CONTROLS_MODEL_TAXONOMY_CURRENT,
    AI_CONTROLS_MODEL_TAXONOMY_VERSIONS,
    AI_CONTROLS_MODEL_ENRICHMENT_CURRENT,
    AI_CONTROLS_MODEL_ENRICHMENT_VERSIONS,
    AI_CONTROLS_MODEL_CLEANED_TEXT_CURRENT,
    AI_CONTROLS_MODEL_CLEANED_TEXT_VERSIONS,
    AI_CONTROLS_MODEL_EMBEDDINGS_CURRENT,
    AI_CONTROLS_MODEL_EMBEDDINGS_VERSIONS,
    # AI Relationship Tables
    AI_CONTROLS_REL_HAS_TAXONOMY,
    AI_CONTROLS_REL_HAS_ENRICHMENT,
    AI_CONTROLS_REL_HAS_CLEANED_TEXT,
    AI_CONTROLS_REL_HAS_EMBEDDINGS,
    # All tables list
    ALL_TABLES,
)

from .setup import (
    create_schema,
    drop_schema,
    reset_schema,
)

__all__ = [
    # Source Reference Tables
    "SRC_CONTROLS_REF_RISK_THEME",
    "SRC_CONTROLS_REF_ORG_FUNCTION",
    "SRC_CONTROLS_REF_ORG_LOCATION",
    "SRC_CONTROLS_REF_SOX_ASSERTION",
    "SRC_CONTROLS_REF_CATEGORY_FLAG",
    # Source Main Tables
    "SRC_CONTROLS_MAIN",
    "SRC_CONTROLS_VERSIONS",
    # Source Relationship Tables
    "SRC_CONTROLS_REL_HAS_RISK_THEME",
    "SRC_CONTROLS_REL_HAS_RELATED_FUNCTION",
    "SRC_CONTROLS_REL_HAS_RELATED_LOCATION",
    "SRC_CONTROLS_REL_HAS_SOX_ASSERTION",
    "SRC_CONTROLS_REL_HAS_CATEGORY_FLAG",
    # AI Model Tables
    "AI_CONTROLS_MODEL_TAXONOMY_CURRENT",
    "AI_CONTROLS_MODEL_TAXONOMY_VERSIONS",
    "AI_CONTROLS_MODEL_ENRICHMENT_CURRENT",
    "AI_CONTROLS_MODEL_ENRICHMENT_VERSIONS",
    "AI_CONTROLS_MODEL_CLEANED_TEXT_CURRENT",
    "AI_CONTROLS_MODEL_CLEANED_TEXT_VERSIONS",
    "AI_CONTROLS_MODEL_EMBEDDINGS_CURRENT",
    "AI_CONTROLS_MODEL_EMBEDDINGS_VERSIONS",
    # AI Relationship Tables
    "AI_CONTROLS_REL_HAS_TAXONOMY",
    "AI_CONTROLS_REL_HAS_ENRICHMENT",
    "AI_CONTROLS_REL_HAS_CLEANED_TEXT",
    "AI_CONTROLS_REL_HAS_EMBEDDINGS",
    # All tables list
    "ALL_TABLES",
    # Setup functions
    "create_schema",
    "drop_schema",
    "reset_schema",
]
