"""add assessment units tables

Revision ID: 629bf70edade
Revises: 001
Create Date: 2026-02-13 22:31:29.167302
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629bf70edade'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('src_au_ref_unit',
    sa.Column('unit_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('src_au_ver_unit',
    sa.Column('ver_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ref_unit_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('function_node_id', sa.Text(), nullable=False),
    sa.Column('location_node_id', sa.Text(), nullable=False),
    sa.Column('location_type', sa.Text(), nullable=False),
    sa.Column('tx_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tx_to', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("location_type IN ('location', 'consolidated')", name='ck_ver_unit_location_type'),
    sa.CheckConstraint("status IN ('Active', 'Inactive')", name='ck_ver_unit_status'),
    sa.CheckConstraint('tx_to IS NULL OR tx_to > tx_from', name='ck_ver_unit_tx_range'),
    sa.ForeignKeyConstraint(['function_node_id'], ['src_orgs_ref_node.node_id'], ),
    sa.ForeignKeyConstraint(['location_node_id'], ['src_orgs_ref_node.node_id'], ),
    sa.ForeignKeyConstraint(['ref_unit_id'], ['src_au_ref_unit.unit_id'], ),
    sa.PrimaryKeyConstraint('ver_id')
    )
    op.create_index('ix_ver_unit_ref_txto', 'src_au_ver_unit', ['ref_unit_id', 'tx_to'], unique=False)
    op.create_index('uq_ver_unit_ref_current', 'src_au_ver_unit', ['ref_unit_id'], unique=True, postgresql_where=sa.text('tx_to IS NULL'))
    op.alter_column('processing_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('processing_jobs', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'records_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'records_processed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'records_new',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'records_changed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'records_unchanged',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processing_jobs', 'records_failed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_rel_child_edge'), 'src_orgs_rel_child', type_='unique')
    op.create_index('uq_rel_child_edge', 'src_orgs_rel_child', ['in_node_id', 'out_node_id', 'tx_from'], unique=True)
    op.drop_constraint(op.f('uq_rel_cross_link_edge'), 'src_orgs_rel_cross_link', type_='unique')
    op.create_index('uq_rel_cross_link_edge', 'src_orgs_rel_cross_link', ['in_node_id', 'out_node_id', 'tx_from'], unique=True)
    op.alter_column('tus_uploads', 'offset',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('tus_uploads', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tus_uploads', 'expected_files',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('upload_batches', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('upload_id_sequence', 'sequence',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_id_sequence', 'sequence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('upload_batches', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tus_uploads', 'expected_files',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tus_uploads', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tus_uploads', 'offset',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('uq_rel_cross_link_edge', table_name='src_orgs_rel_cross_link')
    op.create_unique_constraint(op.f('uq_rel_cross_link_edge'), 'src_orgs_rel_cross_link', ['in_node_id', 'out_node_id', 'tx_from'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_rel_child_edge', table_name='src_orgs_rel_child')
    op.create_unique_constraint(op.f('uq_rel_child_edge'), 'src_orgs_rel_child', ['in_node_id', 'out_node_id', 'tx_from'], postgresql_nulls_not_distinct=False)
    op.alter_column('processing_jobs', 'records_failed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'records_unchanged',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'records_changed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'records_new',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'records_processed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'records_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processing_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('uq_ver_unit_ref_current', table_name='src_au_ver_unit', postgresql_where=sa.text('tx_to IS NULL'))
    op.drop_index('ix_ver_unit_ref_txto', table_name='src_au_ver_unit')
    op.drop_table('src_au_ver_unit')
    op.drop_table('src_au_ref_unit')
    # ### end Alembic commands ###
