"""Add PostgreSQL snapshot tables

Revision ID: e70eef6a4bd3
Revises: 629bf70edade
Create Date: 2026-02-16 12:02:06.044826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70eef6a4bd3'
down_revision: Union[str, None] = '629bf70edade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_snapshots', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_snapshot_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_schedules_is_active', 'snapshot_schedules', ['is_active'], unique=False)
    op.create_index('idx_schedules_next_run_at', 'snapshot_schedules', ['next_run_at'], unique=False)
    op.create_table('postgres_snapshots',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('alembic_version', sa.String(length=32), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restored_count', sa.Integer(), nullable=False),
    sa.Column('last_restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_restored_by', sa.String(length=255), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['snapshot_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_created_at', 'postgres_snapshots', ['created_at'], unique=False)
    op.create_index('idx_snapshots_schedule_id', 'postgres_snapshots', ['schedule_id'], unique=False)
    op.create_index('idx_snapshots_status', 'postgres_snapshots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshots_status', table_name='postgres_snapshots')
    op.drop_index('idx_snapshots_schedule_id', table_name='postgres_snapshots')
    op.drop_index('idx_snapshots_created_at', table_name='postgres_snapshots')
    op.drop_table('postgres_snapshots')
    op.drop_index('idx_schedules_next_run_at', table_name='snapshot_schedules')
    op.drop_index('idx_schedules_is_active', table_name='snapshot_schedules')
    op.drop_table('snapshot_schedules')
    # ### end Alembic commands ###
