import { ControlWithDetails } from './types';

export const MOCK_CONTROLS: ControlWithDetails[] = [
    // ── L1 Controls ──────────────────────────────────────────
    {
        control: {
            control_id: 'CTRL-001',
            control_title: 'Third-Party Vendor Access Review',
            control_description: 'Quarterly review of all vendor accounts with system access privileges to ensure least-privilege compliance and timely deprovisioning of terminated vendors.',
            key_control: true,
            hierarchy_level: 'L1',
            preventative_detective: 'Preventative',
            manual_automated: 'Automated',
            execution_frequency: 'Quarterly',
            control_status: 'Active',
            control_owner: 'Sarah Jenkins',
            valid_from: '2023-01-15',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-GWM', label: 'Global Wealth Management' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [
                { id: 'F-IT', label: 'IT Operations' },
                { id: 'F-PROC', label: 'Procurement' },
            ],
            related_locations: [
                { id: 'L-CA', label: 'Canada' },
                { id: 'L-UK', label: 'United Kingdom' },
            ],
            parent_control_id: null,
            child_control_ids: ['CTRL-002', 'CTRL-004'],
            risk_themes: [{ id: 'RT-CYB-04', name: 'Cyber Security', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L1',
            criteria: {
                what: { yes_no: true, detail: 'Clearly describes vendor access review process.' },
                where: { yes_no: true, detail: 'Specifies all regions with vendor access.' },
                who: { yes_no: true, detail: 'Owner and assessor are identified.' },
                when: { yes_no: true, detail: 'Quarterly frequency is well defined.' },
                why: { yes_no: true, detail: 'Risk rationale linked to cyber security.' },
                what_why: { yes_no: true, detail: 'Clear link between activity and risk.' },
                risk_theme: { yes_no: false, detail: 'Risk theme could be more specific.' },
            },
            linked_control_ids: ['CTRL-003', 'CTRL-006'],
        },
    },
    {
        control: {
            control_id: 'CTRL-003',
            control_title: 'Encryption Key Rotation Policy',
            control_description: 'Annual rotation of master encryption keys for customer databases and validation of key management procedures across all data centers.',
            key_control: true,
            hierarchy_level: 'L1',
            preventative_detective: 'Detective',
            manual_automated: 'Automated',
            execution_frequency: 'Annually',
            control_status: 'Active',
            control_owner: 'Mike K.',
            valid_from: '2022-06-01',
            sox_relevant: false,
        },
        relationships: {
            owning_function: { id: 'F-TECH', label: 'Technology' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [{ id: 'F-DSEC', label: 'Data Security' }],
            related_locations: [
                { id: 'L-US', label: 'United States' },
                { id: 'L-CH', label: 'Switzerland' },
            ],
            parent_control_id: null,
            child_control_ids: ['CTRL-005', 'CTRL-008'],
            risk_themes: [{ id: 'RT-CYB-01', name: 'Cyber Security', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L1',
            criteria: {
                what: { yes_no: true, detail: 'Key rotation process is well documented.' },
                where: { yes_no: true, detail: 'All data centers are in scope.' },
                who: { yes_no: false, detail: 'Key custodians not explicitly named.' },
                when: { yes_no: true, detail: 'Annual rotation schedule defined.' },
                why: { yes_no: true, detail: 'Aligned with data protection regulations.' },
                what_why: { yes_no: false, detail: 'Linkage to specific risk scenario weak.' },
                risk_theme: { yes_no: true, detail: 'Correctly mapped to Cyber Security.' },
            },
            linked_control_ids: ['CTRL-001'],
        },
    },
    {
        control: {
            control_id: 'CTRL-006',
            control_title: 'Client Onboarding KYC Verification',
            control_description: 'Mandatory Know Your Customer verification for all new client accounts including identity validation, sanctions screening, and beneficial ownership checks.',
            key_control: true,
            hierarchy_level: 'L1',
            preventative_detective: 'Preventative',
            manual_automated: 'Manual',
            execution_frequency: 'Per Event',
            control_status: 'Active',
            control_owner: 'Anna Torres',
            valid_from: '2021-03-10',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-COMP', label: 'Compliance' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [
                { id: 'F-OPS', label: 'Operations' },
                { id: 'F-LEGAL', label: 'Legal' },
            ],
            related_locations: [
                { id: 'L-UK', label: 'United Kingdom' },
                { id: 'L-SG', label: 'Singapore' },
            ],
            parent_control_id: null,
            child_control_ids: ['CTRL-007', 'CTRL-011'],
            risk_themes: [
                { id: 'RT-COMP-01', name: 'AML / KYC', taxonomy: 'Compliance' },
                { id: 'RT-COMP-02', name: 'Sanctions', taxonomy: 'Compliance' },
            ],
        },
        ai: {
            type: 'L1',
            criteria: {
                what: { yes_no: true, detail: 'KYC process steps are well defined.' },
                where: { yes_no: true, detail: 'Regional scope clearly stated.' },
                who: { yes_no: true, detail: 'Responsible parties identified.' },
                when: { yes_no: true, detail: 'Trigger event (new client) defined.' },
                why: { yes_no: true, detail: 'Regulatory requirement well documented.' },
                what_why: { yes_no: true, detail: 'Strong link to compliance risk.' },
                risk_theme: { yes_no: true, detail: 'Correctly mapped to AML/KYC.' },
            },
            linked_control_ids: ['CTRL-001'],
        },
    },
    {
        control: {
            control_id: 'CTRL-009',
            control_title: 'Market Risk Limit Monitoring',
            control_description: 'Daily monitoring of trading position limits against approved risk appetite with automated breach alerts and escalation to senior management.',
            key_control: true,
            hierarchy_level: 'L1',
            preventative_detective: 'Detective',
            manual_automated: 'IT-Dependent Manual',
            execution_frequency: 'Daily',
            control_status: 'Active',
            control_owner: 'David Chen',
            valid_from: '2022-01-01',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-RISK', label: 'Risk Management' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [{ id: 'F-TRAD', label: 'Trading' }],
            related_locations: [
                { id: 'L-US', label: 'United States' },
                { id: 'L-UK', label: 'United Kingdom' },
                { id: 'L-HK', label: 'Hong Kong' },
            ],
            parent_control_id: null,
            child_control_ids: ['CTRL-010', 'CTRL-014'],
            risk_themes: [{ id: 'RT-MKT-01', name: 'Market Risk', taxonomy: 'Financial Risk' }],
        },
        ai: {
            type: 'L1',
            criteria: {
                what: { yes_no: true, detail: 'Limit monitoring process documented.' },
                where: { yes_no: true, detail: 'Global scope with regional desks.' },
                who: { yes_no: true, detail: 'Risk officers and traders identified.' },
                when: { yes_no: true, detail: 'Daily monitoring frequency clear.' },
                why: { yes_no: true, detail: 'Regulatory and risk appetite alignment.' },
                what_why: { yes_no: false, detail: 'Could better link to specific risk scenarios.' },
                risk_theme: { yes_no: true, detail: 'Correctly mapped to Market Risk.' },
            },
            linked_control_ids: [],
        },
    },
    {
        control: {
            control_id: 'CTRL-012',
            control_title: 'IT Change Management Approval',
            control_description: 'All production system changes must go through formal change advisory board review with documented approval, rollback plan, and post-implementation verification.',
            key_control: true,
            hierarchy_level: 'L1',
            preventative_detective: 'Preventative',
            manual_automated: 'Automated',
            execution_frequency: 'Per Event',
            control_status: 'Active',
            control_owner: 'Rachel Ng',
            valid_from: '2023-04-01',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-TECH', label: 'Technology' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [
                { id: 'F-OPS', label: 'Operations' },
                { id: 'F-DSEC', label: 'Data Security' },
            ],
            related_locations: [],
            parent_control_id: null,
            child_control_ids: ['CTRL-013'],
            risk_themes: [{ id: 'RT-OPS-01', name: 'IT Operations', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L1',
            criteria: {
                what: { yes_no: true, detail: 'Change management process documented.' },
                where: { yes_no: true, detail: 'All production systems in scope.' },
                who: { yes_no: true, detail: 'CAB members and approvers named.' },
                when: { yes_no: true, detail: 'Per-event trigger clear.' },
                why: { yes_no: true, detail: 'Risk reduction for production stability.' },
                what_why: { yes_no: true, detail: 'Strong linkage to operational risk.' },
                risk_theme: { yes_no: true, detail: 'Correctly mapped to IT Operations.' },
            },
            linked_control_ids: ['CTRL-003'],
        },
    },

    // ── L2 Controls ──────────────────────────────────────────
    {
        control: {
            control_id: 'CTRL-002',
            control_title: 'Vendor Access Log Review',
            control_description: 'Monthly review of vendor access logs to detect unauthorized access patterns and validate compliance with vendor access agreements.',
            key_control: true,
            hierarchy_level: 'L2',
            preventative_detective: 'Detective',
            manual_automated: 'Manual',
            execution_frequency: 'Monthly',
            control_status: 'Active',
            control_owner: 'James Wright',
            valid_from: '2023-02-01',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-GWM', label: 'Global Wealth Management' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [{ id: 'F-IT', label: 'IT Operations' }],
            related_locations: [{ id: 'L-CA', label: 'Canada' }],
            parent_control_id: 'CTRL-001',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-CYB-04', name: 'Cyber Security', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Monthly frequency appropriate for risk level.' },
                preventative_detective: { yes_no: true, detail: 'Correctly identified as detective.' },
                automation_level: { yes_no: false, detail: 'Could benefit from automated log analysis.' },
                followup: { yes_no: true, detail: 'Escalation path for anomalies defined.' },
                escalation: { yes_no: true, detail: 'Senior management notification in place.' },
                evidence: { yes_no: true, detail: 'Log review reports retained.' },
                abbreviations: { yes_no: true, detail: 'No undefined abbreviations found.' },
            },
            linked_control_ids: ['CTRL-004'],
        },
    },
    {
        control: {
            control_id: 'CTRL-004',
            control_title: 'Vendor Onboarding Security Assessment',
            control_description: 'Security assessment of all new vendors before granting system access, including penetration test results and compliance certification review.',
            key_control: true,
            hierarchy_level: 'L2',
            preventative_detective: 'Preventative',
            manual_automated: 'IT-Dependent Manual',
            execution_frequency: 'Per Event',
            control_status: 'Active',
            control_owner: 'Sarah Jenkins',
            valid_from: '2023-03-15',
            sox_relevant: false,
        },
        relationships: {
            owning_function: { id: 'F-GWM', label: 'Global Wealth Management' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [
                { id: 'F-IT', label: 'IT Operations' },
                { id: 'F-DSEC', label: 'Data Security' },
            ],
            related_locations: [],
            parent_control_id: 'CTRL-001',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-CYB-04', name: 'Cyber Security', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Per-event trigger is appropriate.' },
                preventative_detective: { yes_no: true, detail: 'Correctly classified as preventative.' },
                automation_level: { yes_no: true, detail: 'IT-dependent assessment tools used.' },
                followup: { yes_no: false, detail: 'No post-assessment follow-up defined.' },
                escalation: { yes_no: false, detail: 'Missing escalation for failed assessments.' },
                evidence: { yes_no: true, detail: 'Assessment reports archived.' },
                abbreviations: { yes_no: true, detail: 'All abbreviations defined.' },
            },
            linked_control_ids: ['CTRL-002'],
        },
    },
    {
        control: {
            control_id: 'CTRL-005',
            control_title: 'Database Encryption Validation',
            control_description: 'Weekly automated scan to verify encryption-at-rest is enabled on all customer database instances.',
            key_control: false,
            hierarchy_level: 'L2',
            preventative_detective: 'Detective',
            manual_automated: 'Automated',
            execution_frequency: 'Weekly',
            control_status: 'Active',
            control_owner: 'Mike K.',
            valid_from: '2022-07-01',
            sox_relevant: false,
        },
        relationships: {
            owning_function: { id: 'F-TECH', label: 'Technology' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [{ id: 'F-DSEC', label: 'Data Security' }],
            related_locations: [{ id: 'L-US', label: 'United States' }],
            parent_control_id: 'CTRL-003',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-CYB-01', name: 'Cyber Security', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Weekly scanning appropriate for critical data.' },
                preventative_detective: { yes_no: true, detail: 'Detective control correctly labeled.' },
                automation_level: { yes_no: true, detail: 'Fully automated scanning.' },
                followup: { yes_no: true, detail: 'Auto-ticket creation on failure.' },
                escalation: { yes_no: true, detail: 'Critical findings escalated to CISO.' },
                evidence: { yes_no: true, detail: 'Scan reports retained for audit.' },
                abbreviations: { yes_no: false, detail: 'AES-256 and TDE not defined in description.' },
            },
            linked_control_ids: ['CTRL-008'],
        },
    },
    {
        control: {
            control_id: 'CTRL-007',
            control_title: 'KYC Refresh — High Risk Clients',
            control_description: 'Biannual refresh of KYC documentation for high-risk client segments including PEPs and clients from sanctioned jurisdictions.',
            key_control: true,
            hierarchy_level: 'L2',
            preventative_detective: 'Detective',
            manual_automated: 'Manual',
            execution_frequency: 'Biannually',
            control_status: 'Inactive',
            control_owner: 'Anna Torres',
            valid_from: '2021-06-01',
            sox_relevant: false,
        },
        relationships: {
            owning_function: { id: 'F-COMP', label: 'Compliance' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [{ id: 'F-LEGAL', label: 'Legal' }],
            related_locations: [{ id: 'L-UK', label: 'United Kingdom' }],
            parent_control_id: 'CTRL-006',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-COMP-01', name: 'AML / KYC', taxonomy: 'Compliance' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: false, detail: 'Biannual may be insufficient for high-risk.' },
                preventative_detective: { yes_no: true, detail: 'Detective classification appropriate.' },
                automation_level: { yes_no: false, detail: 'Manual process limits scalability.' },
                followup: { yes_no: true, detail: 'Follow-up process for missing docs defined.' },
                escalation: { yes_no: true, detail: 'Escalation to MLRO documented.' },
                evidence: { yes_no: false, detail: 'Evidence retention policy not referenced.' },
                abbreviations: { yes_no: true, detail: 'PEP and MLRO properly defined.' },
            },
            linked_control_ids: ['CTRL-011'],
        },
    },
    {
        control: {
            control_id: 'CTRL-008',
            control_title: 'Certificate Expiry Monitoring',
            control_description: 'Automated monitoring of TLS/SSL certificate expiry dates with 30-day advance alerting and automated renewal for eligible certificates.',
            key_control: true,
            hierarchy_level: 'L2',
            preventative_detective: 'Preventative',
            manual_automated: 'Automated',
            execution_frequency: 'Daily',
            control_status: 'Active',
            control_owner: 'Mike K.',
            valid_from: '2022-08-15',
            sox_relevant: false,
        },
        relationships: {
            owning_function: { id: 'F-TECH', label: 'Technology' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [],
            related_locations: [],
            parent_control_id: 'CTRL-003',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-CYB-01', name: 'Cyber Security', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Daily monitoring is appropriate.' },
                preventative_detective: { yes_no: true, detail: 'Preventative with advance alerting.' },
                automation_level: { yes_no: true, detail: 'Fully automated monitoring and renewal.' },
                followup: { yes_no: true, detail: 'Auto-escalation for non-renewable certs.' },
                escalation: { yes_no: true, detail: 'Multi-tier escalation defined.' },
                evidence: { yes_no: true, detail: 'Alert logs and renewal records kept.' },
                abbreviations: { yes_no: true, detail: 'TLS/SSL defined in description.' },
            },
            linked_control_ids: ['CTRL-005'],
        },
    },
    {
        control: {
            control_id: 'CTRL-010',
            control_title: 'VaR Backtesting Exception Analysis',
            control_description: 'Analysis of Value-at-Risk model backtesting exceptions to identify model weaknesses and trigger recalibration where thresholds are breached.',
            key_control: false,
            hierarchy_level: 'L2',
            preventative_detective: 'Detective',
            manual_automated: 'IT-Dependent Manual',
            execution_frequency: 'Monthly',
            control_status: 'Under Review',
            control_owner: 'David Chen',
            valid_from: '2022-04-01',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-RISK', label: 'Risk Management' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [{ id: 'F-TRAD', label: 'Trading' }],
            related_locations: [{ id: 'L-UK', label: 'United Kingdom' }],
            parent_control_id: 'CTRL-009',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-MKT-01', name: 'Market Risk', taxonomy: 'Financial Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Monthly analysis aligned with regulatory expectations.' },
                preventative_detective: { yes_no: true, detail: 'Detective control for model validation.' },
                automation_level: { yes_no: false, detail: 'Manual analysis could be partially automated.' },
                followup: { yes_no: false, detail: 'Recalibration follow-up not time-bound.' },
                escalation: { yes_no: true, detail: 'Escalation to model risk committee.' },
                evidence: { yes_no: true, detail: 'Exception reports documented.' },
                abbreviations: { yes_no: false, detail: 'VaR not defined in control description.' },
            },
            linked_control_ids: ['CTRL-014'],
        },
    },
    {
        control: {
            control_id: 'CTRL-011',
            control_title: 'Sanctions Screening — Transaction Level',
            control_description: 'Real-time screening of all outgoing wire transfers against OFAC, EU, and UN sanctions lists with automated hold on potential matches.',
            key_control: true,
            hierarchy_level: 'L2',
            preventative_detective: 'Preventative',
            manual_automated: 'Automated',
            execution_frequency: 'Real-time',
            control_status: 'Active',
            control_owner: 'Anna Torres',
            valid_from: '2021-09-01',
            sox_relevant: false,
        },
        relationships: {
            owning_function: { id: 'F-COMP', label: 'Compliance' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [{ id: 'F-OPS', label: 'Operations' }],
            related_locations: [
                { id: 'L-US', label: 'United States' },
                { id: 'L-UK', label: 'United Kingdom' },
            ],
            parent_control_id: 'CTRL-006',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-COMP-02', name: 'Sanctions', taxonomy: 'Compliance' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Real-time screening is best practice.' },
                preventative_detective: { yes_no: true, detail: 'Preventative with automated hold.' },
                automation_level: { yes_no: true, detail: 'Fully automated screening engine.' },
                followup: { yes_no: true, detail: 'Manual review of potential matches defined.' },
                escalation: { yes_no: true, detail: 'Escalation to compliance officer documented.' },
                evidence: { yes_no: true, detail: 'Screening logs and disposition records kept.' },
                abbreviations: { yes_no: true, detail: 'OFAC, EU, UN properly referenced.' },
            },
            linked_control_ids: ['CTRL-007'],
        },
    },
    {
        control: {
            control_id: 'CTRL-013',
            control_title: 'Emergency Change Post-Implementation Review',
            control_description: 'Review of all emergency production changes within 5 business days of implementation to validate proper documentation and risk assessment completion.',
            key_control: false,
            hierarchy_level: 'L2',
            preventative_detective: 'Detective',
            manual_automated: 'Manual',
            execution_frequency: 'Per Event',
            control_status: 'Active',
            control_owner: 'Rachel Ng',
            valid_from: '2023-05-01',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-TECH', label: 'Technology' },
            owning_location: { id: 'L-GLOBAL', label: 'Global' },
            related_functions: [{ id: 'F-OPS', label: 'Operations' }],
            related_locations: [],
            parent_control_id: 'CTRL-012',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-OPS-01', name: 'IT Operations', taxonomy: 'Operational Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Per-event review within 5 days is appropriate.' },
                preventative_detective: { yes_no: true, detail: 'Post-implementation review is detective.' },
                automation_level: { yes_no: false, detail: 'Manual review — no automation.' },
                followup: { yes_no: true, detail: 'Follow-up actions tracked in ITSM tool.' },
                escalation: { yes_no: false, detail: 'No escalation for repeated emergency changes.' },
                evidence: { yes_no: true, detail: 'Review reports stored in change management system.' },
                abbreviations: { yes_no: true, detail: 'No undefined abbreviations.' },
            },
            linked_control_ids: [],
        },
    },
    {
        control: {
            control_id: 'CTRL-014',
            control_title: 'Position Limit Breach Escalation',
            control_description: 'Immediate escalation of trading position limit breaches to desk heads and risk committee with documented remediation plan within 24 hours.',
            key_control: true,
            hierarchy_level: 'L2',
            preventative_detective: 'Detective',
            manual_automated: 'IT-Dependent Manual',
            execution_frequency: 'Per Event',
            control_status: 'Inactive',
            control_owner: 'David Chen',
            valid_from: '2022-02-15',
            sox_relevant: true,
        },
        relationships: {
            owning_function: { id: 'F-RISK', label: 'Risk Management' },
            owning_location: { id: 'L-US', label: 'United States' },
            related_functions: [{ id: 'F-TRAD', label: 'Trading' }],
            related_locations: [{ id: 'L-HK', label: 'Hong Kong' }],
            parent_control_id: 'CTRL-009',
            child_control_ids: [],
            risk_themes: [{ id: 'RT-MKT-01', name: 'Market Risk', taxonomy: 'Financial Risk' }],
        },
        ai: {
            type: 'L2',
            criteria: {
                frequency: { yes_no: true, detail: 'Per-event escalation is appropriate.' },
                preventative_detective: { yes_no: true, detail: 'Detective control for breach response.' },
                automation_level: { yes_no: false, detail: 'IT-dependent but mostly manual.' },
                followup: { yes_no: true, detail: '24-hour remediation plan required.' },
                escalation: { yes_no: true, detail: 'Multi-level escalation to risk committee.' },
                evidence: { yes_no: false, detail: 'Remediation plan retention not specified.' },
                abbreviations: { yes_no: true, detail: 'VaR and PnL properly referenced.' },
            },
            linked_control_ids: ['CTRL-010'],
        },
    },
];
